services:
  mysql:
    image: mysql:8.0
    container_name: book_eating_lion_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: book_eating_lion
      TZ: Asia/Seoul
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake

    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot" ]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
    container_name: book_eating_lion_backend
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=mysql
    depends_on:
      mysql:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_BASE_URL: ""
    container_name: book_eating_lion_frontend
    ports:
      - "5173:80"
    depends_on:
      - backend
