// 백엔드 미연결 시 getBooks / getBookDetail의 fallback으로 사용되는 목 데이터
export const MOCK_BOOKS = [
  {
    bookId: 1,
    title: '달러구트 꿈 백화점',
    author: '이미예',
    publisher: '팩토리나인',
    isbn: '9791165341909',
    category: '소설',
    price: 14500,
    description: '잠들어야만 입장할 수 있는 상점, 달러구트 꿈 백화점에서 벌어지는 따뜻한 이야기.',
    stock: 20,
  },
  {
    bookId: 2,
    title: '불편한 편의점',
    author: '김호연',
    publisher: '나무옆의자',
    isbn: '9791161571188',
    category: '소설',
    price: 14000,
    description: '서울역 앞 작은 편의점을 중심으로 펼쳐지는 사람들의 이야기.',
    stock: 15,
  },
  {
    bookId: 3,
    title: '아몬드',
    author: '손원평',
    publisher: '창비',
    isbn: '9788936455324',
    category: '소설',
    price: 13500,
    description: '감정을 느끼지 못하는 소년 윤재가 세상과 관계 맺는 법을 배우는 성장 소설.',
    stock: 18,
  },
  {
    bookId: 4,
    title: '미드나잇 라이브러리',
    author: '매트 헤이그',
    publisher: '인플루엔셜',
    isbn: '9791191056633',
    category: '소설',
    price: 15800,
    description: '삶과 죽음 사이의 도서관에서 다른 삶을 선택할 수 있다면.',
    stock: 12,
  },
  {
    bookId: 5,
    title: '언어의 온도',
    author: '이기주',
    publisher: '말글터',
    isbn: '9791195829907',
    category: '에세이',
    price: 13000,
    description: '말과 글에 담긴 온기에 대해 이야기하는 에세이.',
    stock: 25,
  },
  {
    bookId: 6,
    title: '완전한 행복',
    author: '정유정',
    publisher: '은행나무',
    isbn: '9788956607911',
    category: '소설',
    price: 15000,
    description: '완전한 행복을 좇는 한 여자의 심리를 그린 서스펜스 소설.',
    stock: 9,
  },
  {
    bookId: 7,
    title: '작별하지 않는다',
    author: '한강',
    publisher: '문학동네',
    isbn: '9788954682152',
    category: '소설',
    price: 15500,
    description: '제주 4·3사건을 배경으로 한 애도와 기억의 이야기.',
    stock: 7,
  },
  {
    bookId: 8,
    title: '역행자',
    author: '자청',
    publisher: '웅진지식하우스',
    isbn: '9788901261127',
    category: '자기계발',
    price: 17000,
    description: '평범한 사람이 부와 자유를 얻기 위한 7단계 자기계발서.',
    stock: 30,
  },
]
