// 백엔드 미연결 시 getBooks / getBookDetail의 fallback으로 사용되는 목 데이터
export const MOCK_BOOKS = [
  {
    bookId: 1,
    title: '달러구트 꿈 백화점',
    author: '이미예',
    publisher: '팩토리나인',
    isbn: '9791165341909',
    category: '소설',
    price: 14500,
    description: '잠들어야만 입장할 수 있는 상점, 달러구트 꿈 백화점에서 벌어지는 따뜻한 이야기.',
    stock: 20,
  },
  {
    bookId: 2,
    title: '불편한 편의점',
    author: '김호연',
    publisher: '나무옆의자',
    isbn: '9791161571188',
    category: '소설',
    price: 14000,
    description: '서울역 앞 작은 편의점을 중심으로 펼쳐지는 사람들의 이야기.',
    stock: 15,
  },
  {
    bookId: 3,
    title: '아몬드',
    author: '손원평',
    publisher: '창비',
    isbn: '9788936455324',
    category: '소설',
    price: 13500,
    description: '감정을 느끼지 못하는 소년 윤재가 세상과 관계 맺는 법을 배우는 성장 소설.',
    stock: 18,
  },
  {
    bookId: 4,
    title: '미드나잇 라이브러리',
    author: '매트 헤이그',
    publisher: '인플루엔셜',
    isbn: '9791191056633',
    category: '소설',
    price: 15800,
    description: '삶과 죽음 사이의 도서관에서 다른 삶을 선택할 수 있다면.',
    stock: 12,
  },
  {
    bookId: 5,
    title: '언어의 온도',
    author: '이기주',
    publisher: '말글터',
    isbn: '9791195829907',
    category: '에세이',
    price: 13000,
    description: '말과 글에 담긴 온기에 대해 이야기하는 에세이.',
    stock: 25,
  },
  {
    bookId: 6,
    title: '완전한 행복',
    author: '정유정',
    publisher: '은행나무',
    isbn: '9788956607911',
    category: '소설',
    price: 15000,
    description: '완전한 행복을 좇는 한 여자의 심리를 그린 서스펜스 소설.',
    stock: 9,
  },
  {
    bookId: 7,
    title: '작별하지 않는다',
    author: '한강',
    publisher: '문학동네',
    isbn: '9788954682152',
    category: '소설',
    price: 15500,
    description: '제주 4·3사건을 배경으로 한 애도와 기억의 이야기.',
    stock: 7,
  },
  {
    bookId: 8,
    title: '역행자',
    author: '자청',
    publisher: '웅진지식하우스',
    isbn: '9788901261127',
    category: '자기계발',
    price: 17000,
    description: '평범한 사람이 부와 자유를 얻기 위한 7단계 자기계발서.',
    stock: 30,
  },
  {
    bookId: 9,
    title: '총, 균, 쇠',
    author: '재레드 다이아몬드',
    publisher: '김영사',
    isbn: '9791188114287',
    category: '역사',
    price: 22000,
    description: '문명의 불균형을 지리와 환경의 관점에서 추적하는 역사 명저.',
    stock: 14,
  },
  {
    bookId: 10,
    title: '역사의 쓸모',
    author: '최태성',
    publisher: '다산초당',
    isbn: '9791190456123',
    category: '역사',
    price: 16000,
    description: '역사 속 인물들의 선택에서 오늘을 살아갈 지혜를 찾는 이야기.',
    stock: 11,
  },
  {
    bookId: 11,
    title: '미움받을 용기',
    author: '기시미 이치로, 고가 후미타케',
    publisher: '인플루엔셜',
    isbn: '9788901219135',
    category: '인문',
    price: 14900,
    description: '아들러 심리학을 대화체로 풀어낸 자기 이해의 인문서.',
    stock: 22,
  },
  {
    bookId: 12,
    title: '정의란 무엇인가',
    author: '마이클 샌델',
    publisher: '와이즈베리',
    isbn: '9788958309980',
    category: '인문',
    price: 18000,
    description: '정의를 둘러싼 철학적 질문들을 다양한 사례로 풀어낸 책.',
    stock: 13,
  },
  {
    bookId: 13,
    title: '코스모스',
    author: '칼 세이건',
    publisher: '사이언스북스',
    isbn: '9788983711892',
    category: '과학',
    price: 23000,
    description: '우주와 인간의 자리를 성찰하게 하는 과학 교양서의 고전.',
    stock: 16,
  },
  {
    bookId: 14,
    title: '이기적 유전자',
    author: '리처드 도킨스',
    publisher: '을유문화사',
    isbn: '9788935600097',
    category: '과학',
    price: 20000,
    description: '유전자의 관점에서 생명과 진화를 설명하는 진화생물학 고전.',
    stock: 10,
  },
  {
    bookId: 15,
    title: '방구석 미술관',
    author: '조원재',
    publisher: '블랙피쉬',
    isbn: '9791165961084',
    category: '미술',
    price: 17500,
    description: '어렵게만 느껴지던 명화를 편안한 입담으로 풀어내는 미술 교양서.',
    stock: 19,
  },
  {
    bookId: 16,
    title: '고흐, 영혼의 편지',
    author: '빈센트 반 고흐',
    publisher: '예담',
    isbn: '9788970132435',
    category: '미술',
    price: 16500,
    description: '고흐가 동생 테오에게 보낸 편지를 통해 그의 삶과 예술을 들여다보는 책.',
    stock: 8,
  },
]
