apiVersion: v1
kind: ConfigMap
metadata:
  name: lion-db-config
  namespace: lion-db
data:
  SPRING_PROFILES_ACTIVE: "prod"
  SERVER_PORT: "8080"
  DB_HOST: "db-service"
  DB_PORT: "3306"
  DB_NAME: # 이름
  AWS_REGION: "ap-northeast-2"
  S3_BUCKET_NAME: # 다이어그램의 AWS S3 버킷명