# apiVersion: v1
# kind: Secret
# metadata:
#   name: backend-secret
#   namespace: lion-app
# type: Opaque
# stringData:
# # 보안을 위해 GitHub Actions의 Secret 사용
#   DB_USERNAME: "${DB_USERNAME}"
#   DB_PASSWORD: "${DB_PASSWORD}"
#   JWT_KEY: "${JWT_KEY}"
#   JWT_KEYRT: "${JWT_KEYRT}"

apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: lion-app
type: Opaque
stringData:
  DB_USERNAME: "root"
  DB_PASSWORD: "1234"
  JWT_KEY: "ThisIsASecretKeyForJWTTokenGeneration12345678"
  JWT_KEYRT: "ThisIsASecretKeyForJWTTokenGeneration12345678"
