apiVersion: v1
kind: Secret
# metadata:
#   name: lion-db-secret
#   namespace: lion-db
# type: Opaque
# data:
    # 보안을 위해 GitHub Actions의 Secret 사용
#   DB_USERNAME: "${DB_USERNAME}"
#   DB_PASSWORD: "${DB_PASSWORD}"
#   # JWT: "${JWT}"

  # 로컬 용
metadata:
  name: springboot-app-secret
  namespace: lion-app
type: Opaque
stringData:
  SPRING_DATASOURCE_PASSWORD: "1234"
---
# env 추가