# 1. Primary DB Service
apiVersion: v1
kind: Service
metadata:
  name: db-primary-service
  namespace: lion-db
spec:
  type: ExternalName
  externalName: db-team3.c3qme6c6e7fj.ap-northeast-2.rds.amazonaws.com
  ports:
  - port: 3306
    protocol: TCP
---

# 2. Read Replica DB Service
apiVersion: v1
kind: Service
metadata:
  name: db-replica-service
  namespace: lion-db
spec:
  type: ExternalName
  externalName: db-team3-read-replica.c3qme6c6e7fj.ap-northeast-2.rds.amazonaws.com
  ports:
  - port: 3306
    protocol: TCP

# 로컬 테스트용 db 컨테이너
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: mysql-deployment
#   namespace: lion-db
#   labels:
#     app: mysql
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: mysql
#   template:
#     metadata:
#       labels:
#         app: mysql
#     spec:
#       containers:
#       - name: mysql
#         image: mysql:8.0
#         ports:
#         - containerPort: 3306
#         env:
#         - name: MYSQL_ROOT_PASSWORD
#           value: "1234"
#         - name: MYSQL_DATABASE
#           value: "testdb"
#         resources:
#           requests:
#             cpu: "250m"
#             memory: "256Mi"
#           limits:
#             cpu: "500m"
#             memory: "512Mi"
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: db-service
#   namespace: lion-db
# spec:
#   type: ClusterIP
#   selector:
#     app: mysql
#   ports:
#   - port: 3306
#     targetPort: 3306
#     protocol: TCP