# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: mvc-app-deployment
#   namespace: prod
#   labels:
#     app: mvc-app
# spec:
#   replicas: 2
#   selector:
#     matchLabels:
#       app: mvc-app
#   template:
#     metadata:
#       labels:
#         app: mvc-app
#     spec:
#       affinity:
#         podAntiAffinity:
#           preferredDuringSchedulingIgnoredDuringExecution:
#           - weight: 100
#             podAffinityTerm:
#               labelSelector:
#                 matchExpressions:
#                 - key: app
#                   operator: In
#                   values:
#                   - mvc-app
#               topologyKey: "kubernetes.io/hostname"
#       containers:
#       - name: mvc-app-container
#         # Amazon ECR 이미지 주소 (다이어그램의 ECR)
#         image: <AWS_ACCOUNT_ID>.dkr.ecr.ap-northeast-2.amazonaws.com/mvc-app:latest
#         imagePullPolicy: Always
#         ports:
#         - containerPort: 8080
        
#         # HPA 오토스케일링 동작을 위한 자원 요구량 명시
#         resources:
#           requests:
#             cpu: "250m"
#             memory: "512Mi"
#           limits:
#             cpu: "500m"
#             memory: "1Gi"

#         # ConfigMap / Secret 환경변수 일괄 주입
#         envFrom:
#         - configMapRef:
#             name: app-config
#         - secretRef:
#             name: app-secret

#         # Health Check
#         livenessProbe:
#           httpGet:
#             path: /actuator/health
#             port: 8080
#           initialDelaySeconds: 30
#           periodSeconds: 10
#         readinessProbe:
#           httpGet:
#             path: /actuator/health
#             port: 8080
#           initialDelaySeconds: 20
#           periodSeconds: 5

#       terminationGracePeriodSeconds: 30

# 로컬용
apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot
  namespace: lion-app
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: springboot
  template:
    metadata:
      labels:
        app: springboot
    spec:
      containers:
        - name: springboot
          image: cheongomabi/fs:4.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /home
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /home
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 3
          resources:
            requests:
              cpu: 250m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
          env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: springboot-config
                  key: SPRING_DATASOURCE_URL
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: springboot-config
                  key: SPRING_DATASOURCE_USERNAME
            - name: SPRING_SQL_INIT_CONTINUE_ON_ERROR
              valueFrom:
                configMapKeyRef:
                  name: springboot-config
                  key: SPRING_SQL_INIT_CONTINUE_ON_ERROR
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: springboot-app-secret
                  key: SPRING_DATASOURCE_PASSWORD
---