# 1. FRONTEND SERVICE
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: lion-app
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
---

# 2. BACKEND SERVICE
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: lion-app
spec:
  type: NodePort
  selector:
    app: backend
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
