# apiVersion: networking.k8s.io/v1
# kind: NetworkPolicy
# metadata:
#   name: allow-mysql-from-backend
#   namespace: lion-db
# spec:
#   podSelector:
#     matchLabels:
#       app: mysql
#   policyTypes:
#   - Ingress
#   ingress:
#   - from:
#     - namespaceSelector:
#         matchLabels:
#           kubernetes.io/metadata.name: lion-app
#       podSelector:
#         matchLabels:
#           app: backend # lion-app 내의 백엔드 Pod만 DB 접근 허용
#     ports:
#     - protocol: TCP
#       port: 3306

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-mysql-from-backend
  namespace: lion-db
spec:
  podSelector:
    matchLabels:
      app: mysql
  policyTypes:
  - Ingress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: lion-app
      podSelector:
        matchLabels:
          app: backend
    ports:
    - protocol: TCP
      port: 3306