server:
  port: 8080

spring:
  application:
    name: book-eating-lion-api
  datasource:
    primary:
      jdbc-url: jdbc:mysql://${DB_PRIMARY_HOST:${DB_HOST:localhost}}:3306/book_eating_lion?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
      username: ${DB_USERNAME:root}
      password: ${DB_PASSWORD:root}
      driver-class-name: com.mysql.cj.jdbc.Driver
    replica:
      jdbc-url: jdbc:mysql://${DB_REPLICA_HOST:${DB_HOST:localhost}}:3306/book_eating_lion?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
      username: ${DB_USERNAME:root}
      password: ${DB_PASSWORD:root}
      driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

jwt:
  secretKey: VGhpc0lzQVNlY3JldEtleUZvckpXVFRva2VuR2VuZXJhdGlvbjEyMzQ1Njc4kw==
  secretKeyRt: VGhpc0lzQVNlY3JldEtleUZvckpXVFRva2VuR2VuZXJhdGlvbjEyMzQ1Njc4kw==

kakaopay:
  secret-key: ${KAKAOPAY_SECRET_KEY:DEVAC1371A30AFB5D8FCFD9A8C0C18B2CC847AC5}
  cid: TC0ONETIME
  api-url: https://open-api.kakaopay.com
