name: Deploy Main to EKS

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'
      - 'frontend/**'
      - 'k8s/**'
      - '.github/workflows/deploy.yml'

env:
  AWS_REGION: "ap-northeast-2"
  EKS_CLUSTER: "[여기에_EKS_클러스터명]"
  ECR_REGISTRY: "[여기에_ECR_주소]"
  BACKEND_REPO: "[여기에_백엔드_ECR_이름]"
  FRONTEND_REPO: "[여기에_프론트엔드_ECR_이름]"
  K8S_YAML_DIR: "./k8s"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x ./backend/gradlew

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push Backend Image
        run: |
          cd ./backend
          IMAGE_TAG=build-${{ github.run_number }}
          docker build -t ${{ env.ECR_REGISTRY }}/${{ env.BACKEND_REPO }}:$IMAGE_TAG -f Dockerfile .
          docker push ${{ env.ECR_REGISTRY }}/${{ env.BACKEND_REPO }}:$IMAGE_TAG

      - name: Build and push Frontend Image
        run: |
          cd ./frontend
          IMAGE_TAG=build-${{ github.run_number }}
          docker build -t ${{ env.ECR_REGISTRY }}/${{ env.FRONTEND_REPO }}:$IMAGE_TAG -f Dockerfile .
          docker push ${{ env.ECR_REGISTRY }}/${{ env.FRONTEND_REPO }}:$IMAGE_TAG

      - name: Update EKS kubeconfig
        run: |
          aws eks update-kubeconfig --name ${{ env.EKS_CLUSTER }} --region ${{ env.AWS_REGION }}

      - name: Substitute Secrets and Apply K8s Resources
        env:
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          JWT_KEY: ${{ secrets.JWT_KEY }}
          JWT_KEYRT: ${{ secrets.JWT_KEYRT }}
        run: |
          envsubst < ${{ env.K8S_YAML_DIR }}/03-secret.yaml | kubectl apply -f -
          kubectl apply -f ${{ env.K8S_YAML_DIR }}

      - name: Update K8s Deployments with new images
        run: |
          IMAGE_TAG=build-${{ github.run_number }}
          
          kubectl set image deployment/backend-deployment \
            backend=${{ env.ECR_REGISTRY }}/${{ env.BACKEND_REPO }}:$IMAGE_TAG -n lion-app
            
          kubectl set image deployment/frontend-deployment \
            frontend=${{ env.ECR_REGISTRY }}/${{ env.FRONTEND_REPO }}:$IMAGE_TAG -n lion-app

      - name: Check Rollout Status
        run: |
          kubectl rollout status deployment/backend-deployment -n lion-app --timeout=300s
          kubectl rollout status deployment/frontend-deployment -n lion-app --timeout=300s