name: deploy account-backend

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout GitHub
        uses: actions/checkout@v4

      - name: Install kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: "v1.25.9"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET }}
          aws-region: ap-northeast-2

      - name: Update EKS kubeconfig
        run: |
          aws eks update-kubeconfig \
            --name my-cluster-jungje \
            --region ap-northeast-2

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push Docker image
        env:
          REGISTRY: 061039804626.dkr.ecr.ap-northeast-2.amazonaws.com
          REPOSITORY: my-ecr-jungje
          IMAGE_TAG: build-${{ github.run_number }}

        run: |
          docker build \
            -t $REGISTRY/$REPOSITORY:$IMAGE_TAG \
            -f ./Dockerfile \
            .

          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG

      - name: Apply Kubernetes resources
        run: |
          kubectl apply -f "./k8s_AWS_https적용후/db_secret_https_AWS.yaml"
          kubectl apply -f "./k8s_AWS_https적용후/redis_https_AWS.yaml"
          kubectl apply -f "./k8s_AWS_https적용후/https_Cert_AWS.yaml"
          kubectl apply -f "./k8s_AWS_https적용후/deploy_https_AWS.yaml"
          kubectl apply -f "./k8s_AWS_https적용후/ingress_https_AWS.yaml"

      - name: Update Deployment image
        env:
          REGISTRY: 061039804626.dkr.ecr.ap-northeast-2.amazonaws.com
          REPOSITORY: my-ecr-jungje
          IMAGE_TAG: build-${{ github.run_number }}

        run: |
          kubectl set image deployment/account-backend \
            account-backend=$REGISTRY/$REPOSITORY:$IMAGE_TAG

      - name: Check Deployment rollout
        run: |
          kubectl rollout status deployment/account-backend \
            --timeout=300s

      - name: Check Kubernetes resources
        run: |
          kubectl get deployment account-backend
          kubectl get pods -l app=account-backend
          kubectl get service account-backend-service
---

name: Java Spring Boot CI/CD with Docker

on:
  push:
    branches: [ "test" ]
    paths:
      - 'backend/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Grant execute permission for gradlew
      run: chmod +x ./backend/gradlew
      continue-on-error: true

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: ./backend
        file: ./backend/Dockerfile
        push: true
        tags: |
          ${{ secrets.DOCKER_USERNAME }}/book-eating-lion-backend:test
          ${{ secrets.DOCKER_USERNAME }}/book-eating-lion-backend:v${{ github.run_number }}
          ${{ secrets.DOCKER_USERNAME }}/book-eating-lion-backend:${{ github.sha }}
---

name: Frontend CI/CD with Docker

on:
  push:
    branches: [ "test" ]
    paths:
      - 'frontend/**'

jobs:
  build-and-push-frontend:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: ./frontend
        file: ./frontend/Dockerfile
        push: true
        tags: |
          ${{ secrets.DOCKER_USERNAME }}/book-eating-lion-frontend:test
          ${{ secrets.DOCKER_USERNAME }}/book-eating-lion-frontend:v${{ github.run_number }}
          ${{ secrets.DOCKER_USERNAME }}/book-eating-lion-frontend:${{ github.sha }}